server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        # Тук казваме на Nginx да търси първо login.html
        index  login.html;
        try_files $uri $uri/ /login.html;
    }
}
