spring.application.name=notifications-service

server.port = 8082

spring.datasource.url=jdbc:mysql://db:3306/school_inventory?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

# ????????? ?? RabbitMQ (Docker ??????????, ????? ?????)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest