# Database Connection (?????? localhost ? 127.0.0.1)
spring.application.name=report-service

spring.datasource.url=jdbc:mysql://db:3306/school_inventory?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

server.port = 8083

jwt.secret=MoitaSuperTainaParolaKoqtoTrqbvaDaEBone32SimvolaLong!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false