# Database Connection (?????? localhost ? 127.0.0.1)
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/school_inventory?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

jwt.secret=MoitaSuperTainaParolaKoqtoTrqbvaDaEBone32SimvolaLong!

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/school_inventory?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false