server:
  port: 9000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true

      routes:
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/auth/**

        - id: request-service
          uri: http://request-service:8084
          predicates:
            - Path=/api/request/**,/api/requests/**,/api/manager/requests/**

        - id: inventory-service
          uri: http://inventory-service:8081
          predicates:
            - Path=/api/equipment/**

        - id: report-service
          uri: http://report-service:8083
          predicates:
            - Path=/api/reports/**

        - id: notifications-service
          uri: http://notification-service:8082
          predicates:
            - Path=/api/notifications/**